### ISSUE TITLE
generation fails when there is no negative prompt

### ISSUE THREAD

**Issue by thot-experiment** [hnmr293/sd-webui-cutoff#1]
## repro steps
1. attempt to generate something with addon enabled and no negative prompt

## error
`ValueError: max() arg is an empty sequence`

Just making this in case someone else runs into the same issue, just make sure to include a negative prompt and everything works fine.

**Comment by hnmr293** [comment]
Thanks for your feedback.
I've fixed it. Update the extension and please try again.
![](https://user-images.githubusercontent.com/120772120/224709703-deb64314-664e-40df-8b81-6cd8ccb19b84.png)
