### ISSUE TITLE
Can't make it work.

### ISSUE THREAD

**Issue by Kuresuto12** [hnmr293/sd-webui-cutoff#24]
**I'm not sure if I am doing something wrong, but I feel like I've followed the steps correctly, apart from my prompt having 100 tokens. 
But no matter how much I cut off, changed settings, tried batches of images, it seems like there is ALWAYS contamination instead.**

> analog style,model shoot style,RAW photo ((close portrait:1.6)) of an edgy and cool profile picture featuring a young man who resembles Sung Jin Woo from the popular webtoon series "Solo Leveling",
> (trimmed` ,orange beard,:1.1),(green eyes:1.1),detailed eyes,
> (black headphones:1.1),blue lightning around the headphones,solo focus,dressed in cool and fashionable attire,long coat, clean white backdrop background,feeling of edginess,sharpness,and coolness,capturing the essence of the character while presenting a visually striking profile picture,
> <lora:detailedeyes:0.9>,
> Negative prompt: Asian-Less-Neg,color contamination,
> Steps: 50, Sampler: DPM++ SDE Karras, CFG scale: 10, Seed: 2077349957, Size: 512x728, Model hash: c194532de5, Model: realMoonAnime_v20, Cutoff enabled: True, Cutoff targets: ["orange", "green", "black", "blue"], Cutoff padding: _</w>, Cutoff weight: 2.0, Cutoff disable_for_neg: True, Cutoff strong: False, Cutoff interpolation: lerp, Lora hashes: "detailedeyes: 3013f7bd7b29", Version: v1.3.1

![00044-2077349957](https://github.com/hnmr293/sd-webui-cutoff/assets/128293430/43349e6e-7034-49c6-bfd8-eed1fc14794b)
The image above is the one with the cutoff, while the one below is without the cutoff.

![00045-2077349957](https://github.com/hnmr293/sd-webui-cutoff/assets/128293430/cc3611fb-3453-4643-a8a9-a36469173b7c)

### Being honest, looks like there was more color contamination on the image with the cutoff activated than the one without it.

**Comment by songib** [comment]
Ye, in my testing, it produces the same img as well, idk.

**Comment by hnmr293** [comment]
Thank you for your feedbacks.
I think it has been fixed.
If not, please reopen this issue.
