### ISSUE TITLE
Unable to see the difference

### ISSUE THREAD

**Issue by Miczu** [hnmr293/sd-webui-cutoff#26]
Hello, I'm having hard time figuring out if this extensions is working for me. Turning it off and on or changing the weight slider just doesn't produce differences I'm able to notice. Logs appear to be doing something, so not sure if this is intended behavior or not.

![xyz_grid-0031-3748336610](https://github.com/hnmr293/sd-webui-cutoff/assets/48890028/62e8804a-027a-4a09-be21-ffca4f5361a7)
![image](https://github.com/hnmr293/sd-webui-cutoff/assets/48890028/1bfd21c7-c441-4288-87bc-cfef38d9b90f)

**Comment by Miczu** [comment]
So based on https://github.com/hnmr293/sd-webui-cutoff/issues/7#issuecomment-1492857249 my example wouldn't work, as there is only token group (no commas).

I'm still seeing something wrong with X/Y/Z Plot.

I took example from the pain page:

Prompt: a cute girl, white shirt with green tie, red shoes, blue hair, yellow eyes, pink skirt
Target tokens: white, green, red, blue, yellow, pink

![xyz_grid-0032-2619856562](https://github.com/hnmr293/sd-webui-cutoff/assets/48890028/376c8587-3c48-4b56-948a-3ae438b775e8)

There are no differences on the plot, but if I render -0.5 manually enabled/disabled, there are differences.

Enabled: True
![grid-0120](https://github.com/hnmr293/sd-webui-cutoff/assets/48890028/ad859bc6-7534-47fe-b2cd-b4577a3a134d)

Enabled: False
![grid-0121](https://github.com/hnmr293/sd-webui-cutoff/assets/48890028/0ff51c8f-051f-4e02-85fc-9438aff273b8)

X/Y/Z Plot is great tool in figuring out how different settings work, so it not working is really problematic.

**Comment by mez0ru** [comment]
I noticed that if you turn it off (after you turned it on) it will stay on for the rest of all generations (probably a bug). Same if I turn it on after I generate something, it won't work. You have to turn it on before ANY generation. It's a bug I noticed. So either way you have to restart webui before either turning it off or on.

**Comment by hnmr293** [comment]
Thank you for your feedbacks.
I think it has been fixed.
If not, please reopen this issue.
