### ISSUE TITLE
Assertion error with SDXL

### ISSUE THREAD

**Issue by wogam** [hnmr293/sd-webui-cutoff#28]
>     Traceback (most recent call last):
>       File "C:\stable-diffusion-webui\modules\call_queue.py", line 57, in f
>         res = list(func(*args, **kwargs))
>       File "C:\stable-diffusion-webui\modules\call_queue.py", line 36, in f
>         res = func(*args, **kwargs)
>       File "C:\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
>         processed = processing.process_images(p)
>       File "C:\stable-diffusion-webui\modules\processing.py", line 734, in process_images
>         res = process_images_inner(p)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
>         return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
>       File "C:\stable-diffusion-webui\modules\processing.py", line 858, in process_images_inner
>         p.setup_conds()
>       File "C:\stable-diffusion-webui\modules\processing.py", line 1314, in setup_conds
>         super().setup_conds()
>       File "C:\stable-diffusion-webui\modules\processing.py", line 469, in setup_conds
>         self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, total_steps, [self.cached_uc], self.extra_network_data)
>       File "C:\stable-diffusion-webui\modules\processing.py", line 455, in get_conds_with_caching
>         cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling)
>       File "C:\stable-diffusion-webui\modules\prompt_parser.py", line 188, in get_learned_conditioning
>         conds = model.get_learned_conditioning(texts)
>       File "C:\stable-diffusion-webui\modules\sd_models_xl.py", line 31, in get_learned_conditioning
>         c = self.conditioner(sdxl_conds, force_zero_embeddings=['txt'] if force_zero_negative_prompt else [])
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1547, in _call_impl
>         hook_result = hook(self, args, result)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-cutoff\scripts\cutoff.py", line 94, in hook
>         assert isinstance(mod, CLIP)
>     AssertionError

Prompt: A man wearing a red shirt next to a blue space monkey
Negatives: Text, 3d

Cutoff tokens: red,blue

A1111 1.6

Happens with any prompt, not just this one.

**Comment by hnmr293** [comment]
Thanks for your feedback.
Please update Cutoff to newest version.
`Extensions` -> `Check for updates` -> `Apply and restart UI`
