### ISSUE TITLE
what to put in "padding token"??? hints?? please?

### ISSUE THREAD

**Issue by PowerfulShell** [hnmr293/sd-webui-cutoff#6]
what to put in "padding token"??? hints?? please?

**Comment by PowerfulShell** [comment]
what is ID and Single token, these words means nothing to me sorry......

**Comment by hnmr293** [comment]
Short answer:
If you are not familiar with CLIP, do not touch there.

Lengthy answer:
Input a token or its ID what you want to use as the padding token.
It is used for replacing each `target token`.

For instance, if you put `,` (comma) to `padding token` and put `red` to `target tokens`, the word `red` in your prompt is replaced to `,`.

I wrote implementation details here: #5.

If it is blank, the default value `_` (underbar) is used.

**Comment by PowerfulShell** [comment]
https://github.com/hnmr293/sd-webui-cutoff/issues/5

thanks!!! this clarify everything!!! good job but please put it on the readme.md ::))) so noob like me can read,, but sucks at finding them other than frontpage LOL

**Comment by hnmr293** [comment]
I have updated Readme. Thank you!
