### ISSUE TITLE
ComfyUI requires a CutOff node

### ISSUE THREAD

**Issue by xueqing0622** [hnmr293/sd-webui-cutoff#9]
Hello, cutoff is a good extension, because the most troublesome aspect of stable diffusion is color pollution. Recently, due to work reasons, we have to transfer the workflow from auto111 to comfyUI. However, cutoff is essential. If the author or some code master has time, PLS create a cutoff node for comfyUI,

Thank you. I wish you have a nice day!

**Comment by BlenderNeko** [comment]
I've written a comparable implementation for ComfyUI that you can find [here](https://github.com/BlenderNeko/ComfyUI_Cutoff)

**Comment by xueqing0622** [comment]
oh, thanks a lot, It is very useful! cheers 👍👍👍👍👍👍👍
